language: node_js

node_js:
  - "0.11"
  - "0.10"

install:
  - npm install

before_script:
  - npm run build

script:
  - npm test

notifications:
  hipchat:
    rooms:
      secure: MhEbcSEc98GJyuLYAPNZ8Tp0Hu7+KRjnO1JBpNjhRkCgQyxax8vWaq1TOBFDH+bILWax5aD2wBue0QlUjBo5ICJvGD4LZRsiOTInio2AhfE+gOp+YEseJhlaG+zDI0N92q+eZbsGGCC+X6yGovzMt78AKS1MaYAgYTEt75cVobQ=
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
    format: html
