language: node_js

node_js:
  - "0.10"

script:
  - npm run bower
  - npm test

notifications:
  hipchat:
    rooms:
      secure: ESxkkaOtS8hKBKzh42t59T7Ky3Tn2PYH/26MbysrI1EOwU9o/C6cOwMjy90hHgEnVcipOMQk0wQhjmuFvGRpU0G5HGocASm3CnPOwMFa4WMGd6ZNmO2sJp7gtPpy65uC+ej4IPshPT7rIPgidygREX2hhQwtg1Nv7jkwhgOrjY4=
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
    format: html
